name: neighbayes
channels:
  - conda-forge
dependencies:
  - libpysal
  - esda
  - formulaic
  - pymc
  - arviz
  - spreg
  - statsmodels
  - geopandas
  - geodatasets
  - lazy_loader
  - fastprogress
  - scikit-sparse
  # optional
# - blackjax
# - numpyro
# - pip
#   - pip:
