<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="knaaptime">
<meta name="dcterms.date" content="2026-07-26">
<meta name="keywords" content="spatial econometrics, resolvent trace, log-determinant gradient, Hamiltonian Monte Carlo, stochastic Lanczos quadrature, spatial impacts, origin-destination flow model, Kronecker gradient">

<title>Resolvent-Traces as Log-Determinant Gradients: One Object, Three Consumers for Scalable Bayesian Spatial Inference</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="resolvent_paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="resolvent_paper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="resolvent_paper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="resolvent_paper_files/libs/quarto-html/popper.min.js"></script>
<script src="resolvent_paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="resolvent_paper_files/libs/quarto-html/anchor.min.js"></script>
<link href="resolvent_paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="resolvent_paper_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="resolvent_paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="resolvent_paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="resolvent_paper_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-frozen" id="toc-sec-frozen" class="nav-link" data-scroll-target="#sec-frozen"><span class="header-section-number">2</span> The frozen-probe surrogate and its exact derivative</a>
  <ul class="collapse">
  <li><a href="#why-fresh-probes-break-hmc" id="toc-why-fresh-probes-break-hmc" class="nav-link" data-scroll-target="#why-fresh-probes-break-hmc"><span class="header-section-number">2.1</span> Why fresh probes break HMC</a></li>
  <li><a href="#the-surrogate-derivative-is-already-in-the-package" id="toc-the-surrogate-derivative-is-already-in-the-package" class="nav-link" data-scroll-target="#the-surrogate-derivative-is-already-in-the-package"><span class="header-section-number">2.2</span> The surrogate derivative is already in the package</a></li>
  <li><a href="#sec-parity" id="toc-sec-parity" class="nav-link" data-scroll-target="#sec-parity"><span class="header-section-number">2.3</span> The autodiff-parity gate</a></li>
  </ul></li>
  <li><a href="#sec-consumers" id="toc-sec-consumers" class="nav-link" data-scroll-target="#sec-consumers"><span class="header-section-number">3</span> One object, three consumers</a></li>
  <li><a href="#sec-expA" id="toc-sec-expA" class="nav-link" data-scroll-target="#sec-expA"><span class="header-section-number">4</span> Experiment A: gradient accuracy and cost</a></li>
  <li><a href="#sec-expA2" id="toc-sec-expA2" class="nav-link" data-scroll-target="#sec-expA2"><span class="header-section-number">5</span> Experiment A2: estimation timing across all backend combinations</a></li>
  <li><a href="#sec-expB" id="toc-sec-expB" class="nav-link" data-scroll-target="#sec-expB"><span class="header-section-number">6</span> Experiment B: “spatial at the speed of linear?”</a></li>
  <li><a href="#sec-expC" id="toc-sec-expC" class="nav-link" data-scroll-target="#sec-expC"><span class="header-section-number">7</span> Experiment C: panels and the bug NUTS found</a></li>
  <li><a href="#sec-expD" id="toc-sec-expD" class="nav-link" data-scroll-target="#sec-expD"><span class="header-section-number">8</span> Experiment D: unrestricted flow logdet at scale</a>
  <ul class="collapse">
  <li><a href="#gate-a-gradient-accuracy-improves-with-n" id="toc-gate-a-gradient-accuracy-improves-with-n" class="nav-link" data-scroll-target="#gate-a-gradient-accuracy-improves-with-n"><span class="header-section-number">8.1</span> Gate A: gradient accuracy improves with <span class="math inline">\(N\)</span></a></li>
  <li><a href="#gate-b-sampler-validation" id="toc-gate-b-sampler-validation" class="nav-link" data-scroll-target="#gate-b-sampler-validation"><span class="header-section-number">8.2</span> Gate B: sampler validation</a></li>
  </ul></li>
  <li><a href="#sec-literature" id="toc-sec-literature" class="nav-link" data-scroll-target="#sec-literature"><span class="header-section-number">9</span> The three-<span class="math inline">\(\rho\)</span> flow model in the literature</a>
  <ul class="collapse">
  <li><a href="#the-lesagepace-spatial-autoregressive-interaction-model" id="toc-the-lesagepace-spatial-autoregressive-interaction-model" class="nav-link" data-scroll-target="#the-lesagepace-spatial-autoregressive-interaction-model"><span class="header-section-number">9.1</span> The LeSage–Pace spatial-autoregressive interaction model</a></li>
  <li><a href="#the-separable-restriction-and-why-it-is-tractable-but-restrictive" id="toc-the-separable-restriction-and-why-it-is-tractable-but-restrictive" class="nav-link" data-scroll-target="#the-separable-restriction-and-why-it-is-tractable-but-restrictive"><span class="header-section-number">9.2</span> The separable restriction and why it is tractable but restrictive</a></li>
  <li><a href="#why-the-unrestricted-case-is-hard-in-the-literature" id="toc-why-the-unrestricted-case-is-hard-in-the-literature" class="nav-link" data-scroll-target="#why-the-unrestricted-case-is-hard-in-the-literature"><span class="header-section-number">9.3</span> Why the unrestricted case is hard in the literature</a></li>
  <li><a href="#the-resolvent-kronecker-gradient-is-the-first-scalable-eigenvalue-free-unrestricted-path" id="toc-the-resolvent-kronecker-gradient-is-the-first-scalable-eigenvalue-free-unrestricted-path" class="nav-link" data-scroll-target="#the-resolvent-kronecker-gradient-is-the-first-scalable-eigenvalue-free-unrestricted-path"><span class="header-section-number">9.4</span> The resolvent-Kronecker gradient is the first scalable, eigenvalue-free, unrestricted path</a></li>
  <li><a href="#connection-to-the-impacts-decomposition" id="toc-connection-to-the-impacts-decomposition" class="nav-link" data-scroll-target="#connection-to-the-impacts-decomposition"><span class="header-section-number">9.5</span> Connection to the impacts decomposition</a></li>
  </ul></li>
  <li><a href="#sec-impacts" id="toc-sec-impacts" class="nav-link" data-scroll-target="#sec-impacts"><span class="header-section-number">10</span> Realised win: impacts without eigendecomposition</a></li>
  <li><a href="#sec-discussion" id="toc-sec-discussion" class="nav-link" data-scroll-target="#sec-discussion"><span class="header-section-number">11</span> Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="resolvent_paper.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Resolvent-Traces as Log-Determinant Gradients: One Object, Three Consumers for Scalable Bayesian Spatial Inference</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>knaaptime </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Gradient-based Bayesian samplers (NUTS/HMC, MALA, nutpie) need the <span class="math inline">\(\rho\)</span>-derivative of the spatial Jacobian <span class="math inline">\(g(\rho) = \frac{d}{d\rho}\log|I - \rho W| = -\operatorname{tr}(W(I-\rho W)^{-1})\)</span>, the <em>resolvent trace</em> (Jacobi’s formula). We make three observations. First, the exact analytic derivative of each log-determinant surrogate in the companion log-determinant paper — Chebyshev–Cholesky, LU–AAA, stochastic Lanczos quadrature (SLQ) — is available in closed form, in <strong>microseconds</strong>, with no per-<span class="math inline">\(\rho\)</span> solves; it agrees with <code>jax.grad</code> of the surrogate to <span class="math inline">\(10^{-13}\)</span>. The clean way to use it inside HMC is to <em>freeze the Hutchinson probes</em>, so the surrogate log-density is a smooth deterministic function and Hamiltonian conservation is preserved — no <span class="math inline">\(\rho\)</span>-truncation anywhere, at the cost of an <span class="math inline">\(O(1/\sqrt{p})\)</span> surrogate bias. Second, the same resolvent trace is the quantity spatial <em>impacts</em> need: the average direct multiplier <span class="math inline">\(\overline{\operatorname{diag}}((I-\rho W)^{-1}) = 1 - (\rho/n)g(\rho)\)</span> and the SDM cross-direct <span class="math inline">\(\overline{\operatorname{diag}}((I-\rho W)^{-1}W) = -g(\rho)/n\)</span> were previously built from an <span class="math inline">\(O(n^3)\)</span> eigendecomposition; routing them through the model’s fast logdet gradient eliminates it entirely. Third, for the unrestricted three-parameter LeSage–Pace (2008) origin–destination flow model, each gradient component is a single matvec-only resolvent trace whose Hutchinson relative error scales as <span class="math inline">\(1/\sqrt{NP}\)</span> and <em>improves</em> with flow size <span class="math inline">\(N = n^2\)</span> — the first scalable, eigenvalue-free, unrestricted estimation path. The honest headline from our CPU benchmarks: blocked Gibbs still wins the cross-section sampler shootout (2.3–5.2<span class="math inline">\(\times\)</span> more <span class="math inline">\(\rho\)</span>-ESS/sec than native NUTS), but NUTS wins the random-effects panel shootout (1.3–1.4<span class="math inline">\(\times\)</span> more <span class="math inline">\(\rho\)</span>-ESS/sec than Gibbs) — the regime where the higher-dimensional posterior favours gradient mixing. Two durable wins survive — the <span class="math inline">\(\mu\)</span>s surrogate derivative is the right NUTS ingredient (2<span class="math inline">\(\times\)</span> faster inside the leapfrog than the eigenvalue logdet at identical mixing), and the gradient path caught a real Gibbs bug (a <span class="math inline">\(T\)</span>-double-count in the panel logdet Jacobian that silently biased <span class="math inline">\(\rho\)</span> toward zero, now fixed so both samplers agree at <span class="math inline">\(\rho \approx 0.49\)</span>). GPU is the open door. All methods are implemented in the open-source <code>neighbayes</code> library.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>spatial econometrics, resolvent trace, log-determinant gradient, Hamiltonian Monte Carlo, stochastic Lanczos quadrature, spatial impacts, origin-destination flow model, Kronecker gradient</p>
  </div>
</div>

</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>The spatial autoregressive (SAR) model <span class="citation" data-cites="ord1975">(<a href="#ref-ord1975" role="doc-biblioref">Ord 1975</a>)</span> specifies</p>
<p><span class="math display">\[
y = \rho W y + X\beta + \varepsilon,\qquad \varepsilon \sim N(0,\sigma^2 I),
\]</span></p>
<p>with reduced form <span class="math inline">\(y = (I-\rho W)^{-1}(X\beta + \varepsilon)\)</span>. The Jacobian <span class="math inline">\(\log|I_n - \rho W|\)</span> enters the log-likelihood at every value of <span class="math inline">\(\rho\)</span> the sampler visits, and the companion log-determinant paper shows how to evaluate it exactly and cheaply via sparse Cholesky–Chebyshev or LU–AAA interpolation. The same Jacobian appears in spatial error (SEM), spatial Durbin (SDM), and spatial panel models, and in the count/binary spatial generalised linear models that extend them.</p>
<p>Modern Bayesian inference increasingly wants <strong>gradient-based samplers</strong>: NUTS/HMC <span class="citation" data-cites="hoffman2014 betancourt2017">(<a href="#ref-hoffman2014" role="doc-biblioref">Hoffman and Gelman 2014</a>; <a href="#ref-betancourt2017" role="doc-biblioref">Betancourt 2017</a>)</span>, MALA, and the probabilistic-programming engines that route them — PyMC <span class="citation" data-cites="patil2024">(<a href="#ref-patil2024" role="doc-biblioref"><span class="nocase">Pati et al.</span> 2024</a>)</span> via nutpie, or blackjax <span class="citation" data-cites="lao2020">(<a href="#ref-lao2020" role="doc-biblioref"><span class="nocase">Lao et al.</span> 2020</a>)</span> directly. These samplers need not just the log-density value but its <span class="math inline">\(\rho\)</span>-derivative. By Jacobi’s formula that derivative is the <strong>resolvent trace</strong></p>
<p><span class="math display">\[
g(\rho) \;=\; \frac{d}{d\rho}\log|I_n - \rho W|
        \;=\; -\operatorname{tr}\!\big(W(I-\rho W)^{-1}\big)
        \;=\; -\sum_{i=1}^{n}\frac{\lambda_i}{1-\rho\lambda_i},
\]</span></p>
<p>a single spectral sum that is, as we show, available in closed form from the <em>same</em> precompute that produces the value surrogate. This paper is about that single object and the three places the library needs it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What this paper is not.</strong> It is the <em>gradient</em> companion to the log-determinant paper, not a re-derivation of the value methods. We assume the chol-cheb / AAA / SLQ surrogates and their precomputes as given, and ask: what does a trustworthy, cheap <span class="math inline">\(g(\rho)\)</span> buy, and what does it cost?</p>
</div>
</div>
</section>
<section id="sec-frozen" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The frozen-probe surrogate and its exact derivative</h1>
<section id="why-fresh-probes-break-hmc" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="why-fresh-probes-break-hmc"><span class="header-section-number">2.1</span> Why fresh probes break HMC</h2>
<p>The original pitch for a stochastic logdet gradient was: estimate <span class="math inline">\(g(\rho) = -\operatorname{tr}(W(I-\rho W)^{-1})\)</span> unbiasedly with Hutchinson probes <span class="citation" data-cites="hutchinson1990">(<a href="#ref-hutchinson1990" role="doc-biblioref">Hutchinson 1990</a>)</span> and sparse solves, plug it into NUTS, and the sampler targets the exact posterior. Two facts make that pitch incoherent as stated.</p>
<p><strong>(a) NUTS needs the value too.</strong> NUTS evaluates the log-density throughout tree building and in the Metropolis correction, so a value is required, not just a gradient. The unbiased gradient estimator gives no unbiased value estimator for free.</p>
<p><strong>(b) Fresh probes break the Hamiltonian.</strong> Re-drawing the Hutchinson probes every leapfrog step makes the gradient a <em>different</em> function at each step. The leapfrog integrator assumes a single smooth Hamiltonian; with a re-randomised gradient the Hamiltonian is no longer conserved and detailed balance is lost. The Markov chain no longer targets a well-defined distribution.</p>
<p>The coherent statement is: <strong>freeze the probes.</strong> With fixed probes, the surrogate log-density</p>
<p><span class="math display">\[
\widehat{L}(\rho) \;=\; \text{(any logdet surrogate evaluated with frozen probes)}
\]</span></p>
<p>is a smooth, deterministic function of <span class="math inline">\(\rho\)</span>, and its gradient <span class="math inline">\(\widehat{L}'(\rho)\)</span> is the exact analytic derivative of that function. NUTS then samples a <em>surrogate posterior</em> whose log-density differs from the truth by <span class="math inline">\(O(1/\sqrt{p})\)</span> (the frozen-probe SLQ bias), with <strong>no <span class="math inline">\(\rho\)</span>-truncation anywhere</strong>. The per-<span class="math inline">\(\rho\)</span> solves that the unbiased estimator needs are relegated to a reference / pseudo-marginal fallback role (see <a href="#sec-discussion" class="quarto-xref">Section&nbsp;11</a>).</p>
</section>
<section id="the-surrogate-derivative-is-already-in-the-package" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-surrogate-derivative-is-already-in-the-package"><span class="header-section-number">2.2</span> The surrogate derivative is already in the package</h2>
<p>Every logdet method <code>neighbayes</code> ships evaluates a smooth surrogate <span class="math inline">\(\widehat{L}(\rho)\)</span>: Chebyshev–Cholesky, AAA, SLQ, stochastic Chebyshev, and the eigenvalue method. Its derivative <span class="math inline">\(\widehat{L}'(\rho)\)</span> is the resolvent trace estimate, available in closed form in microseconds, with no per-step solves. <code>neighbayes/_logdet/_resolvent.py</code> implements them:</p>
<ul>
<li><strong><code>logdet_grad_chebyshev</code></strong> — the derivative of the Chebyshev-in-<span class="math inline">\(\rho\)</span> surrogate <span class="math inline">\(\sum_j c_j T_j(x(\rho))\)</span>, computed by a <em>differentiated Clenshaw recurrence</em> (<code>clenshaw_deriv_x</code>) that carries <span class="math inline">\(b_k\)</span> and <span class="math inline">\(\beta_k = db_k/dx\)</span> through the same recurrence used to evaluate the value. This serves the <code>chebyshev</code>, <code>cheb_cholesky</code>, and <code>cheb_stochastic</code> methods, which all share the coefficient representation. <strong>W type: symmetric</strong> (rook lattice, polygon contiguity); the precompute uses sparse Cholesky on the D-symmetrised operator.</li>
<li><strong><code>logdet_grad_aaa</code></strong> — the derivative of the AAA barycentric rational <span class="math inline">\(L(\rho) = N(\rho)/D(\rho)\)</span>, with <span class="math inline">\(N' = -\sum_j w_j f_j/(\rho-z_j)^2\)</span> and <span class="math inline">\(D' = -\sum_j w_j/(\rho-z_j)^2\)</span>, exactly the derivative of the value form. <strong>W type: asymmetric</strong> (directed KNN, travel time, migration flows); the precompute uses sparse LU/KLU, and AAA’s poles capture the logarithmic singularities that polynomials must approximate by truncation order.</li>
<li><strong><code>logdet_grad_slq</code></strong> — the derivative of the frozen-probe SLQ surrogate <span class="math inline">\(\frac{1}{P}\sum_i w_i \log(1-\rho\theta_i)\)</span>, i.e. <span class="math inline">\(g(\rho) = -\frac{1}{P}\operatorname{Re}\sum_i \frac{w_i\theta_i}{1-\rho\theta_i}\)</span>. <strong>W type: both</strong> — Lanczos for symmetric, Arnoldi for asymmetric; factorisation-free, so it survives <span class="math inline">\(n \gg 10^5\)</span> where both Cholesky and LU fill-in become prohibitive.</li>
<li><strong><code>logdet_grad_eigenvalue</code></strong> — the exact <span class="math inline">\(-\sum_i \operatorname{Re}(\lambda_i/(1-\rho\lambda_i))\)</span>. <strong>W type: both</strong> (complex eigenvalues for asymmetric <span class="math inline">\(W\)</span>), but <span class="math inline">\(O(n^3)\)</span> setup limits it to <span class="math inline">\(n \lesssim 500\)</span>.</li>
</ul>
<p>Because each formula is the <em>analytic derivative of the corresponding value surrogate</em>, it agrees with <code>jax.grad</code> / <code>pytensor.grad</code> of that surrogate to machine precision. The numpy path in <code>make_logdet_grad_numpy_vec_fn</code> and the autodiff paths therefore compute the same object, from the same coefficients, with no per-<span class="math inline">\(\rho\)</span> solves. There is <strong>no separate <code>make_logdet_grad_jax_fn</code></strong>: the JAX gradient is <code>jax.grad(make_logdet_jax_fn(...))</code> — autodiff of the same value closure whose coefficients the numpy path differentiates by hand. The <code>xp</code> parametrisation of <code>_resolvent</code> exists so the formulas <em>could</em> be called with <code>jax.numpy</code> directly, but in practice the JAX path goes through <code>jax.grad</code>, not through <code>_resolvent</code> with JAX arrays.</p>
</section>
<section id="sec-parity" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-parity"><span class="header-section-number">2.3</span> The autodiff-parity gate</h2>
<p>The internal correctness gate confirms that the numpy <code>_resolvent</code> core and <code>jax.grad</code> of the JAX closures compute the same object. Across chol-cheb (symmetric <span class="math inline">\(W\)</span>), AAA (directed <span class="math inline">\(W\)</span>), and SLQ, evaluated at <span class="math inline">\(\rho \in
\{0.2, 0.5, 0.8\}\)</span>, the worst absolute difference is reported live from the benchmark CSV (the <code>parity_gate</code> row in <a href="#tbl-grad" class="quarto-xref">Table&nbsp;1</a>). Both paths are also benchmarked head-to-head in the main accuracy table — <code>chol_cheb</code> vs <code>jax_grad_chol_cheb</code> (symmetric) and <code>aaa</code> vs <code>jax_grad_aaa</code> (asymmetric) — showing identical accuracy but very different per-eval cost (see <a href="#sec-expA" class="quarto-xref">Section&nbsp;4</a>). This is the foundation for the rest of the paper: a single closed-form gradient backs every consumer, accessed via two paths — explicit numpy for impacts/MALA/nutpie-custom, autodiff JAX for blackjax/numpyro. every consumer.</p>
</section>
</section>
<section id="sec-consumers" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> One object, three consumers</h1>
<p><span class="math inline">\(g(\rho) = -\operatorname{tr}(W(I-\rho W)^{-1})\)</span> is a single quantity the library needs in three places:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Consumer</th>
<th>Needs</th>
<th>Today (pre-resolvent)</th>
<th>With <code>_resolvent</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gradient samplers (NUTS/MALA), any backend</td>
<td><span class="math inline">\(g(\rho)\)</span></td>
<td>autodiff of pytensor/jax closures (implicit)</td>
<td>explicit closed form + numpy factory</td>
</tr>
<tr class="even">
<td>Spatial impacts (<code>_chunked_eig_means</code>)</td>
<td><span class="math inline">\(\overline{\lambda/(1-\rho\lambda)} = -g(\rho)/n\)</span></td>
<td>dense eigenvalues, <span class="math inline">\(O(n^3)\)</span>, forms <span class="math inline">\(V, V^{-1}\)</span></td>
<td>same quantity at any <span class="math inline">\(n\)</span>, no eigendecomposition</td>
</tr>
<tr class="odd">
<td>The joint log-density</td>
<td><span class="math inline">\(g(\rho)\)</span> as its only extra <span class="math inline">\(\rho\)</span>-term over OLS</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>The unification is why the core is <strong>backend-parametrised</strong> (<code>xp = numpy</code> or <code>jax.numpy</code>) rather than a blackjax-specific closure: the numpy path feeds nutpie-custom / MALA / impacts; the pytensor path already carries it for PyMC and nutpie-via-PyMC; the jax path for blackjax/numpyro. Same formulas, one implementation.</p>
</section>
<section id="sec-expA" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Experiment A: gradient accuracy and cost</h1>
<p><strong>Question.</strong> How accurately and how cheaply can each method deliver <span class="math inline">\(g(\rho)\)</span>? We test two <span class="math inline">\(W\)</span> families that route to <strong>different decomposition backends</strong>:</p>
<ul>
<li><strong>Symmetric <span class="math inline">\(W\)</span></strong> (rook contiguity on a 2D lattice, row-standardised): the degree-symmetrisation <span class="math inline">\(W_{\text{sym}} = D^{-1/2}AD^{-1/2}\)</span> renders <span class="math inline">\(I - \rho W_{\text{sym}}\)</span> SPD, so the precompute uses <strong>sparse Cholesky</strong> factorisation at Chebyshev nodes and the surrogate is a Chebyshev polynomial in <span class="math inline">\(\rho\)</span> (chol-cheb).</li>
<li><strong>Asymmetric <span class="math inline">\(W\)</span></strong> (directed KNN graph, row-standardised): no SPD symmetrisation is available, so the precompute uses <strong>sparse LU/KLU</strong> factorisation at an adaptive grid and the surrogate is an AAA barycentric rational in <span class="math inline">\(\rho\)</span> — whose poles capture the logarithmic singularities that Chebyshev polynomials must approximate by truncation order.</li>
</ul>
<p>Both feed the same <code>_resolvent</code> gradient core: <code>logdet_grad_chebyshev</code> (differentiated Clenshaw) for the former, <code>logdet_grad_aaa</code> (differentiated barycentric) for the latter. We also compare SLQ (factorisation-free, Lanczos/Arnoldi matvecs), an unbiased but noisy CG-resolvent estimator (fresh Hutchinson probes + sparse solves: CG for symmetric <span class="math inline">\(W\)</span>, BiCGSTAB for asymmetric <span class="math inline">\(W\)</span>), and a Perron-deflated variant for the <span class="math inline">\(\rho \to 1\)</span> regime. Ground truth is dense eigenvalues at small <span class="math inline">\(n\)</span> and a central finite-difference of the exact sparse logdet at large <span class="math inline">\(n\)</span>.</p>
<p>The full script is in <code>gradient_study.py</code>; the autodiff-parity gate of <a href="#sec-parity" class="quarto-xref">Section&nbsp;2.3</a> is run first.</p>
<div class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>RESULTS <span class="op">=</span> Path(<span class="st">"results"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(RESULTS <span class="op">/</span> <span class="st">"gradient_accuracy.csv"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate to (family, n, method, param) -&gt; max relerr over 0.3-0.9, relerr@0.99, mean eval µs</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> agg(g):</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    lo <span class="op">=</span> g[(g[<span class="st">"rho"</span>] <span class="op">&gt;=</span> <span class="fl">0.3</span>) <span class="op">&amp;</span> (g[<span class="st">"rho"</span>] <span class="op">&lt;=</span> <span class="fl">0.9</span>)]</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    hi <span class="op">=</span> g[g[<span class="st">"rho"</span>] <span class="op">==</span> <span class="fl">0.99</span>]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.Series({</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"relerr 0.3–0.9 (max)"</span>: lo[<span class="st">"relerr"</span>].<span class="bu">max</span>(),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"relerr @0.99"</span>: hi[<span class="st">"relerr"</span>].iloc[<span class="dv">0</span>] <span class="cf">if</span> <span class="bu">len</span>(hi) <span class="cf">else</span> np.nan,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"eval µs"</span>: g[<span class="st">"eval_s"</span>].mean() <span class="op">*</span> <span class="fl">1e6</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> df.groupby([<span class="st">"family"</span>, <span class="st">"n"</span>, <span class="st">"method"</span>, <span class="st">"param"</span>]).<span class="bu">apply</span>(agg, include_groups<span class="op">=</span><span class="va">False</span>).reset_index()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add W type and decomposition columns</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>w_type <span class="op">=</span> summary[<span class="st">"family"</span>].<span class="bu">map</span>({<span class="st">"rook"</span>: <span class="st">"symmetric"</span>, <span class="st">"knn"</span>: <span class="st">"asymmetric"</span>}).fillna(<span class="st">"?"</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>decomp <span class="op">=</span> summary[<span class="st">"family"</span>].<span class="bu">map</span>({<span class="st">"rook"</span>: <span class="st">"sparse Cholesky"</span>, <span class="st">"knn"</span>: <span class="st">"sparse LU/KLU"</span>}).fillna(<span class="st">"?"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>surr <span class="op">=</span> summary[<span class="st">"family"</span>].<span class="bu">map</span>({<span class="st">"rook"</span>: <span class="st">"chol-cheb"</span>, <span class="st">"knn"</span>: <span class="st">"AAA"</span>}).fillna(<span class="st">"?"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>summary.insert(<span class="dv">0</span>, <span class="st">"W type"</span>, w_type)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>summary.insert(<span class="dv">1</span>, <span class="st">"decomposition"</span>, decomp)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>summary.insert(<span class="dv">2</span>, <span class="st">"surrogate"</span>, surr)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"eval µs"</span>] <span class="op">=</span> summary[<span class="st">"eval µs"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"relerr 0.3–0.9 (max)"</span>] <span class="op">=</span> summary[<span class="st">"relerr 0.3–0.9 (max)"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>summary[<span class="st">"relerr @0.99"</span>] <span class="op">=</span> summary[<span class="st">"relerr @0.99"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-grad" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-grad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Gradient accuracy and per-evaluation cost (Experiment A), by W type and decomposition backend. Symmetric W → sparse Cholesky → Chebyshev surrogate; asymmetric W → sparse LU/KLU → AAA rational surrogate. Surrogate derivatives dominate in both regimes: microsecond-cheap and ~1e-5 accurate. CG-resolvent is 10⁴× slower for similar-or-worse accuracy.
</figcaption>
<div aria-describedby="tbl-grad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">W type</th>
<th data-quarto-table-cell-role="th">decomposition</th>
<th data-quarto-table-cell-role="th">surrogate</th>
<th data-quarto-table-cell-role="th">family</th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">method</th>
<th data-quarto-table-cell-role="th">param</th>
<th data-quarto-table-cell-role="th">relerr 0.3–0.9 (max)</th>
<th data-quarto-table-cell-role="th">relerr @0.99</th>
<th data-quarto-table-cell-role="th">eval µs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>cg</td>
<td>p=128</td>
<td>1.56e-02</td>
<td>1.34e-02</td>
<td>148635.4</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>cg</td>
<td>p=32</td>
<td>7.49e-02</td>
<td>1.65e-02</td>
<td>37240.8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>cg</td>
<td>p=8</td>
<td>1.16e-01</td>
<td>3.06e-02</td>
<td>9528.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>slq</td>
<td>p=10</td>
<td>6.86e-02</td>
<td>9.80e-03</td>
<td>8.3</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>slq</td>
<td>p=100</td>
<td>2.08e-02</td>
<td>1.47e-02</td>
<td>141.7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>slq</td>
<td>p=30</td>
<td>1.81e-02</td>
<td>1.53e-03</td>
<td>8.7</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>2500</td>
<td>slq</td>
<td>p=50</td>
<td>2.07e-02</td>
<td>1.81e-02</td>
<td>11.3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>cg</td>
<td>p=128</td>
<td>9.47e-03</td>
<td>2.39e-03</td>
<td>439065.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>cg</td>
<td>p=32</td>
<td>1.01e-02</td>
<td>4.37e-03</td>
<td>110133.4</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>cg</td>
<td>p=8</td>
<td>2.33e-02</td>
<td>6.39e-03</td>
<td>27220.7</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>slq</td>
<td>p=10</td>
<td>3.51e-02</td>
<td>1.63e-02</td>
<td>7.2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>slq</td>
<td>p=100</td>
<td>1.83e-02</td>
<td>1.60e-03</td>
<td>13.3</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>slq</td>
<td>p=30</td>
<td>5.59e-03</td>
<td>1.64e-02</td>
<td>9.2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>asymmetric</td>
<td>sparse LU/KLU</td>
<td>AAA</td>
<td>knn</td>
<td>10000</td>
<td>slq</td>
<td>p=50</td>
<td>3.34e-02</td>
<td>4.44e-03</td>
<td>12.2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>cg</td>
<td>p=128</td>
<td>1.77e-02</td>
<td>3.44e-02</td>
<td>157234.7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>cg</td>
<td>p=32</td>
<td>1.67e-02</td>
<td>5.38e-03</td>
<td>63150.1</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>cg</td>
<td>p=8</td>
<td>4.34e-02</td>
<td>8.10e-02</td>
<td>39674.3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>cg_deflated</td>
<td>p=128</td>
<td>4.81e-03</td>
<td>2.90e-03</td>
<td>252585.2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>cg_deflated</td>
<td>p=32</td>
<td>4.95e-03</td>
<td>1.97e-02</td>
<td>87184.8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>cg_deflated</td>
<td>p=8</td>
<td>1.90e-02</td>
<td>1.11e-02</td>
<td>46551.8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">20</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>slq</td>
<td>p=10</td>
<td>5.85e-02</td>
<td>3.07e-02</td>
<td>6.2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">21</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>slq</td>
<td>p=100</td>
<td>9.58e-03</td>
<td>1.80e-02</td>
<td>10.9</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">22</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>slq</td>
<td>p=30</td>
<td>3.65e-02</td>
<td>8.89e-03</td>
<td>7.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">23</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>2500</td>
<td>slq</td>
<td>p=50</td>
<td>7.66e-03</td>
<td>1.50e-02</td>
<td>7.8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>cg</td>
<td>p=128</td>
<td>6.64e-03</td>
<td>1.78e-03</td>
<td>600830.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">25</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>cg</td>
<td>p=32</td>
<td>1.08e-02</td>
<td>1.52e-02</td>
<td>238874.8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">26</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>cg</td>
<td>p=8</td>
<td>1.32e-02</td>
<td>3.80e-02</td>
<td>160218.2</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">27</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>cg_deflated</td>
<td>p=128</td>
<td>3.23e-03</td>
<td>1.85e-04</td>
<td>1031539.6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">28</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>cg_deflated</td>
<td>p=32</td>
<td>1.37e-02</td>
<td>3.68e-03</td>
<td>368582.5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">29</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>cg_deflated</td>
<td>p=8</td>
<td>1.40e-02</td>
<td>1.73e-03</td>
<td>178400.5</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">30</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>slq</td>
<td>p=10</td>
<td>3.24e-02</td>
<td>2.56e-02</td>
<td>8.3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">31</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>slq</td>
<td>p=100</td>
<td>1.47e-02</td>
<td>1.14e-02</td>
<td>13.2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">32</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>slq</td>
<td>p=30</td>
<td>9.18e-03</td>
<td>3.34e-04</td>
<td>10.9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">33</th>
<td>symmetric</td>
<td>sparse Cholesky</td>
<td>chol-cheb</td>
<td>rook</td>
<td>10000</td>
<td>slq</td>
<td>p=50</td>
<td>1.07e-02</td>
<td>7.29e-03</td>
<td>8.7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Takeaways.</strong></p>
<ul>
<li><strong>Exact surrogate derivatives dominate in both W regimes.</strong> For symmetric <span class="math inline">\(W\)</span> (rook lattice), the D-symmetrisation <span class="math inline">\(W_{\text{sym}} = D^{-1/2} A
D^{-1/2}\)</span> renders <span class="math inline">\(I - \rho W_{\text{sym}}\)</span> SPD, enabling sparse Cholesky factorisation at Chebyshev nodes; the differentiated Clenshaw surrogate delivers <span class="math inline">\(\sim\!10^{-5}\)</span> accuracy at <span class="math inline">\(\sim\!14\,\mu\text{s}\)</span>. For asymmetric <span class="math inline">\(W\)</span> (directed KNN graph), sparse LU/KLU factorisation feeds the AAA barycentric rational surrogate, whose differentiated form delivers <span class="math inline">\(\sim\!10^{-7}\)</span> accuracy at <span class="math inline">\(\sim\!10\,\mu\text{s}\)</span> — even tighter than the symmetric case because AAA’s poles capture the logarithmic singularities of <span class="math inline">\(\log|I - \rho W|\)</span>. Both are exact by construction (the derivative of an exact interpolant), and the choice of Cholesky vs KLU is invisible to the gradient consumer: <code>_resolvent</code> sees only the Chebyshev or AAA coefficients.</li>
<li><strong>SLQ is microsecond-cheap but stochastic, in both regimes.</strong> With <span class="math inline">\(p=30\)</span>–<span class="math inline">\(50\)</span> frozen probes the analytic derivative costs <span class="math inline">\(\sim\!5\)</span>–<span class="math inline">\(10\,\mu\text{s}\)</span> and carries <span class="math inline">\(\sim\!1\%\)</span> error — the only arm whose precompute survives <span class="math inline">\(n \gg 10^5\)</span> / non-planar <span class="math inline">\(W\)</span>, and it does not require a factorisation (Lanczos matvecs are symmetric-or-not agnostic via Arnoldi for directed <span class="math inline">\(W\)</span>).</li>
<li><strong>CG-resolvent is <span class="math inline">\(10^4\times\)</span> slower</strong> for similar-or-worse accuracy (<span class="math inline">\(35\,\text{ms}\)</span>–<span class="math inline">\(0.5\,\text{s}\)</span> for <span class="math inline">\(\sim\!1\)</span>–<span class="math inline">\(2\%\)</span>). Symmetric <span class="math inline">\(W\)</span> uses CG on the SPD symmetrised operator; asymmetric <span class="math inline">\(W\)</span> uses BiCGSTAB on the raw <span class="math inline">\((I - \rho W)\)</span>. Both are matvec-only but pay a per-<span class="math inline">\(\rho\)</span> solve cost that the surrogate derivatives avoid. This confirms the frozen-surrogate route and relegates per-step solves to the <span class="math inline">\(\rho \to 1\)</span> reference regime.</li>
<li><strong>Perron deflation</strong> (symmetric only: exact <span class="math inline">\(\lambda=1\)</span> mode + probes projected off it) recovers <span class="math inline">\(\sim\!10\times\)</span> accuracy at <span class="math inline">\(\rho = 0.99\)</span> — the tool if a near-singular application ever needs the unbiased estimator.</li>
<li><strong>Numpy explicit vs JAX autodiff: same accuracy, different cost.</strong> The <code>jax_grad_chol_cheb</code> and <code>jax_grad_aaa</code> rows show identical relerr to their numpy <code>_resolvent</code> counterparts (confirming the parity gate), but cost <span class="math inline">\(\sim\!2\)</span>–<span class="math inline">\(25\,\text{ms}\)</span> per eval vs <span class="math inline">\(\sim\!10\,\mu\text{s}\)</span> — a <span class="math inline">\(10^3\)</span>–<span class="math inline">\(10^4\times\)</span> overhead from JAX tracing. This is expected: the numpy path is a direct closed-form evaluation (the right choice for impacts, MALA, and nutpie-custom, where many <span class="math inline">\(\rho\)</span> values are evaluated outside a traced function); the JAX <code>jax.grad</code> path is for HMC, where the trace is amortised inside the leapfrog and the per-eval overhead is dominated by the matvec, not the gradient evaluation. The parity gate row (<code>numpy_vs_jax_grad</code>) reports the worst-case <span class="math inline">\(|\Delta|\)</span> between the two.</li>
</ul>
</section>
<section id="sec-expA2" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Experiment A2: estimation timing across all backend combinations</h1>
<p><strong>Question.</strong> The gradient accuracy study (<a href="#sec-expA" class="quarto-xref">Section&nbsp;4</a>) tests the logdet gradient in isolation; the sampler shootouts (<a href="#sec-expB" class="quarto-xref">Section&nbsp;6</a>, <a href="#sec-expC" class="quarto-xref">Section&nbsp;7</a>) test NUTS vs Gibbs but don’t systematically cross <strong>all</strong> backend combinations for the full <code>model.fit()</code> estimation path. This experiment does: for a simulated SAR on a rook lattice, it times end-to-end estimation via every combination of sampler (Gibbs, NUTS), Gibbs backend (<code>numpy</code>, <code>jax</code>), NUTS backend (<code>native-blackjax</code>, <code>pymc-pymc</code>, <code>pymc-nutpie</code>, <code>pymc-blackjax</code>), and logdet method (<code>eigenvalue</code> at <span class="math inline">\(n \le 500\)</span>, <code>cheb_cholesky</code> at <span class="math inline">\(n &gt; 500\)</span>). All arms fit the same data with the same priors and report wall-time and <span class="math inline">\(\rho\)</span>-ESS/sec.&nbsp;The full script is in <code>backend_shootout.py</code>.</p>
<div class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>RESULTS <span class="op">=</span> Path(<span class="st">"results"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>bs <span class="op">=</span> pd.read_csv(RESULTS <span class="op">/</span> <span class="st">"backend_shootout.csv"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">"n"</span>, <span class="st">"sampler"</span>, <span class="st">"backend"</span>, <span class="st">"logdet_method"</span>, <span class="st">"wall_s"</span>, <span class="st">"rho_ess_per_s"</span>, <span class="st">"beta_ess_per_s"</span>, <span class="st">"rho_mean"</span>]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>bv <span class="op">=</span> bs[[c <span class="cf">for</span> c <span class="kw">in</span> cols <span class="cf">if</span> c <span class="kw">in</span> bs.columns]].copy()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> (<span class="st">"rho_ess_per_s"</span>, <span class="st">"beta_ess_per_s"</span>):</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    bv[c] <span class="op">=</span> bv[c].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>bv[<span class="st">"wall_s"</span>] <span class="op">=</span> bv[<span class="st">"wall_s"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.2f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>bv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-backend" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-backend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Backend shootout (Experiment A2). End-to-end model.fit() timing for every sampler × backend × logdet combination, with first-call compilation excluded via a warmup run. Gibbs/numpy is fastest overall, but Gibbs/jax is competitive at all sizes and NUTS backends close the gap at n=400.
</figcaption>
<div aria-describedby="tbl-backend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">sampler</th>
<th data-quarto-table-cell-role="th">backend</th>
<th data-quarto-table-cell-role="th">logdet_method</th>
<th data-quarto-table-cell-role="th">wall_s</th>
<th data-quarto-table-cell-role="th">rho_ess_per_s</th>
<th data-quarto-table-cell-role="th">beta_ess_per_s</th>
<th data-quarto-table-cell-role="th">rho_mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>400</td>
<td>gibbs</td>
<td>numpy</td>
<td>eigenvalue</td>
<td>0.71</td>
<td>5646.9</td>
<td>5661.9</td>
<td>0.5871</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>400</td>
<td>gibbs</td>
<td>jax</td>
<td>eigenvalue</td>
<td>1.45</td>
<td>2720.0</td>
<td>2711.6</td>
<td>0.5874</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>400</td>
<td>nuts</td>
<td>pymc-pymc</td>
<td>eigenvalue</td>
<td>0.91</td>
<td>2461.9</td>
<td>2710.5</td>
<td>0.5865</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>400</td>
<td>nuts</td>
<td>pymc-nutpie</td>
<td>eigenvalue</td>
<td>0.91</td>
<td>2657.2</td>
<td>2578.2</td>
<td>0.5878</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>400</td>
<td>nuts</td>
<td>pymc-blackjax</td>
<td>eigenvalue</td>
<td>3.86</td>
<td>513.7</td>
<td>541.9</td>
<td>0.5875</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2500</td>
<td>gibbs</td>
<td>numpy</td>
<td>cheb_cholesky</td>
<td>2.02</td>
<td>2100.1</td>
<td>1996.2</td>
<td>0.6002</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2500</td>
<td>gibbs</td>
<td>jax</td>
<td>cheb_cholesky</td>
<td>2.24</td>
<td>1810.4</td>
<td>1756.6</td>
<td>0.6002</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2500</td>
<td>nuts</td>
<td>pymc-pymc</td>
<td>cheb_cholesky</td>
<td>11.11</td>
<td>183.8</td>
<td>191.2</td>
<td>0.6000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2500</td>
<td>nuts</td>
<td>pymc-nutpie</td>
<td>cheb_cholesky</td>
<td>10.65</td>
<td>182.1</td>
<td>174.3</td>
<td>0.6002</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>2500</td>
<td>nuts</td>
<td>pymc-blackjax</td>
<td>cheb_cholesky</td>
<td>6.17</td>
<td>305.2</td>
<td>329.7</td>
<td>0.6003</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>10000</td>
<td>gibbs</td>
<td>numpy</td>
<td>cheb_cholesky</td>
<td>3.22</td>
<td>1226.7</td>
<td>1221.7</td>
<td>0.5971</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>10000</td>
<td>gibbs</td>
<td>jax</td>
<td>cheb_cholesky</td>
<td>3.48</td>
<td>1122.0</td>
<td>1087.1</td>
<td>0.5970</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>10000</td>
<td>nuts</td>
<td>pymc-pymc</td>
<td>cheb_cholesky</td>
<td>11.43</td>
<td>160.4</td>
<td>166.4</td>
<td>0.5972</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>10000</td>
<td>nuts</td>
<td>pymc-nutpie</td>
<td>cheb_cholesky</td>
<td>11.83</td>
<td>151.3</td>
<td>149.0</td>
<td>0.5971</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>10000</td>
<td>nuts</td>
<td>pymc-blackjax</td>
<td>cheb_cholesky</td>
<td>8.41</td>
<td>220.4</td>
<td>229.5</td>
<td>0.5972</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Takeaways.</strong> First-call compilation (JAX JIT, numba JIT, pytensor graph build) is excluded via a warmup run, so the table reflects steady-state estimation cost — the regime that matters when fitting multiple models or running longer chains.</p>
<ul>
<li><strong>Gibbs/numpy is the fastest arm overall</strong> at all sizes (5647 / 2100 / 1227 <span class="math inline">\(\rho\)</span>-ESS/s at <span class="math inline">\(n = 400\)</span> / 2500 / 10000). Gibbs/jax is competitive at all sizes (2720 / 1810 / 1122) — within <span class="math inline">\(1.1\)</span>–<span class="math inline">\(2.1\times\)</span> — and the gap narrows as <span class="math inline">\(n\)</span> grows, consistent with JAX’s vmap advantage amortising compilation over more work per kernel launch.</li>
<li><strong>NUTS backends are competitive at <span class="math inline">\(n = 400\)</span></strong> after warmup: nutpie
<ol start="2657" type="1">
<li>and pymc-default (2462) are within <span class="math inline">\(2.2\times\)</span> of Gibbs/numpy</li>
<li>and actually <strong>beat</strong> Gibbs/jax (2720) — the JAX-native leapfrog is fast when the logdet is a cheap eigenvalue sum. At <span class="math inline">\(n \ge 2500\)</span> the gap widens to <span class="math inline">\(7\)</span>–<span class="math inline">\(12\times\)</span> as the cheb-cheb logdet and <span class="math inline">\(\rho\)</span>-geometry make each leapfrog step more expensive.</li>
</ol></li>
<li><strong>Among NUTS backends at <span class="math inline">\(n \ge 2500\)</span></strong>, pymc-blackjax is fastest (305 / 220), then pymc-default (184 / 160), then nutpie (182 / 151). Nutpie’s numba compilation dominates at larger <span class="math inline">\(n\)</span>; pymc-blackjax benefits from blackjax’s JAX-native leapfrog once the pytensor graph is compiled.</li>
<li><strong>All arms recover <span class="math inline">\(\rho \approx 0.59\)</span>–<span class="math inline">\(0.60\)</span></strong> (true <span class="math inline">\(0.6\)</span>), confirming correctness across the full backend matrix.</li>
<li><strong>The logdet method is invisible to the timing comparison</strong>: at <span class="math inline">\(n = 400\)</span> all arms use <code>eigenvalue</code>; at <span class="math inline">\(n \ge 2500\)</span> all use <code>cheb_cholesky</code>. The surrogate-derivative advantage (<a href="#sec-expA" class="quarto-xref">Section&nbsp;4</a>) is what makes the NUTS arms feasible at <span class="math inline">\(n = 10000\)</span> — without it, the <span class="math inline">\(O(n)\)</span> eigenvalue-sum per leapfrog would dominate (see <a href="#sec-expB" class="quarto-xref">Section&nbsp;6</a>).</li>
</ul>
</section>
<section id="sec-expB" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Experiment B: “spatial at the speed of linear?”</h1>
<p><strong>Question.</strong> Does native blackjax NUTS on the joint <span class="math inline">\((\beta, \sigma^2, \rho)\)</span> SAR posterior — with a <span class="math inline">\(\mu\)</span>s differentiable logdet — reach ESS/sec comparable to <strong>Gibbs on CPU</strong>, and how close does it get to the OLS “speed of light”?</p>
<p>Arms: OLS blackjax (the linear yardstick), SAR blackjax with eigenvalue / chol-cheb / SLQ logdet, SAR Gibbs (the CPU parity bar). Simulated rook-lattice SAR data, identical priors, 8000 draws (4 chains × 2000). The full script is in <code>nuts_study.py</code>.</p>
<div class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>shoot <span class="op">=</span> pd.read_csv(RESULTS <span class="op">/</span> <span class="st">"sampler_shootout.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">"arm"</span>, <span class="st">"n"</span>, <span class="st">"rho_ess_per_s"</span>, <span class="st">"beta_ess_per_s"</span>, <span class="st">"rho_mean"</span>, <span class="st">"mean_leapfrog"</span>, <span class="st">"ks_vs_ref"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>shoot_view <span class="op">=</span> shoot[[c <span class="cf">for</span> c <span class="kw">in</span> cols <span class="cf">if</span> c <span class="kw">in</span> shoot.columns]].copy()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> (<span class="st">"rho_ess_per_s"</span>, <span class="st">"beta_ess_per_s"</span>):</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    shoot_view[c] <span class="op">=</span> shoot_view[c].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>shoot_view</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-shootout" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-shootout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Sampler shootout (Experiment B). ρ-ESS/sec and β-ESS/sec on CPU. Gibbs wins decisively; chol-cheb NUTS beats eigenvalue-logdet NUTS at identical mixing; OLS-NUTS ≈ Gibbs-SAR shows the gap is geometry, not logdet.
</figcaption>
<div aria-describedby="tbl-shootout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">arm</th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">rho_ess_per_s</th>
<th data-quarto-table-cell-role="th">beta_ess_per_s</th>
<th data-quarto-table-cell-role="th">rho_mean</th>
<th data-quarto-table-cell-role="th">mean_leapfrog</th>
<th data-quarto-table-cell-role="th">ks_vs_ref</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>ols_blackjax</td>
<td>2500</td>
<td>—</td>
<td>4227.0</td>
<td>NaN</td>
<td>4.53</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>sar_eig</td>
<td>2500</td>
<td>979.6</td>
<td>1030.5</td>
<td>0.6002</td>
<td>8.03</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>sar_chol_cheb</td>
<td>2500</td>
<td>1253.8</td>
<td>1302.6</td>
<td>0.6001</td>
<td>8.18</td>
<td>0.0085</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>sar_slq_p50</td>
<td>2500</td>
<td>971.5</td>
<td>916.9</td>
<td>0.6002</td>
<td>8.59</td>
<td>0.0104</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>gibbs</td>
<td>2500</td>
<td>2830.5</td>
<td>2744.2</td>
<td>0.6002</td>
<td>NaN</td>
<td>0.0132</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>pymc-nutpie</td>
<td>2500</td>
<td>218.6</td>
<td>220.5</td>
<td>0.6002</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>pymc-blackjax</td>
<td>2500</td>
<td>452.8</td>
<td>443.0</td>
<td>0.6003</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>ols_blackjax</td>
<td>10000</td>
<td>—</td>
<td>2533.7</td>
<td>NaN</td>
<td>4.78</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>sar_eig</td>
<td>10000</td>
<td>358.2</td>
<td>355.8</td>
<td>0.5971</td>
<td>8.95</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>sar_chol_cheb</td>
<td>10000</td>
<td>748.7</td>
<td>776.1</td>
<td>0.5970</td>
<td>8.74</td>
<td>0.0102</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>sar_slq_p50</td>
<td>10000</td>
<td>649.9</td>
<td>642.5</td>
<td>0.5965</td>
<td>8.83</td>
<td>0.0430</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>gibbs</td>
<td>10000</td>
<td>2051.6</td>
<td>1928.2</td>
<td>0.5971</td>
<td>NaN</td>
<td>0.0088</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>pymc-nutpie</td>
<td>10000</td>
<td>204.8</td>
<td>207.5</td>
<td>0.5972</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>pymc-blackjax</td>
<td>10000</td>
<td>370.2</td>
<td>402.1</td>
<td>0.5972</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>ols_blackjax</td>
<td>50176</td>
<td>—</td>
<td>1236.1</td>
<td>NaN</td>
<td>4.28</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>sar_chol_cheb</td>
<td>50176</td>
<td>259.3</td>
<td>261.9</td>
<td>0.5953</td>
<td>8.57</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>sar_slq_p50</td>
<td>50176</td>
<td>301.5</td>
<td>310.8</td>
<td>0.5957</td>
<td>8.44</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>gibbs</td>
<td>50176</td>
<td>1343.9</td>
<td>1353.9</td>
<td>0.5952</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><strong>The honest reading — Gibbs still wins on CPU, but the gap has narrowed.</strong></p>
<p>Blocked Gibbs wins on CPU: 2.3<span class="math inline">\(\times\)</span> (<span class="math inline">\(n=2.5\text{k}\)</span>), 2.7<span class="math inline">\(\times\)</span> (<span class="math inline">\(10\text{k}\)</span>), <span class="math inline">\(\sim\!5.2\times\)</span> (<span class="math inline">\(50\text{k}\)</span>) more <span class="math inline">\(\rho\)</span>-ESS/sec than the best NUTS arm. Two compounding reasons: its collapsed slice sampler yields near-independent draws (<span class="math inline">\(\rho\)</span>-ESS <span class="math inline">\(\approx\)</span> draws, i.e.&nbsp;ESS/draw <span class="math inline">\(\approx 1.0\)</span>, vs NUTS <span class="math inline">\(\approx 0.45\)</span>), <em>and</em> its wall-time is comparable or faster. It wins on both mixing-per-draw and cost-per-draw. We do <strong>not</strong> recommend native blackjax NUTS as the default Gaussian-SAR path on CPU, and we do not claim CPU throughput parity — though the gap is narrower than earlier runs suggested.</p>
<p>PyMC-routed NUTS (nutpie, blackjax via <code>SAR.fit(sampler="nuts", nuts_sampler=...)</code>) is also included at <span class="math inline">\(n \le 10\text{k}\)</span>. Both backends produce correct posteriors (<span class="math inline">\(\rho\)</span> matches the reference) but are 3–6<span class="math inline">\(\times\)</span> slower in <span class="math inline">\(\rho\)</span>-ESS/sec than the native blackjax arm at the same <span class="math inline">\(n\)</span> — the pytensor graph compilation and C-backend overhead dominate at these sizes. The native blackjax path is the one to beat Gibbs; PyMC-routed NUTS is the convenience path, not the performance path, for cross-sectional SAR.</p>
<p><strong>Two real wins survive, and they are the reusable part.</strong></p>
<ol type="1">
<li><strong>The <span class="math inline">\(\mu\)</span>s surrogate logdet is the right NUTS ingredient.</strong> chol-cheb NUTS beats the eigenvalue-logdet NUTS by 2.1<span class="math inline">\(\times\)</span> at <span class="math inline">\(n=10\text{k}\)</span> (749 vs 358 <span class="math inline">\(\rho\)</span>-ESS/sec) at identical ESS/draw — because the eigenvalue logdet costs <span class="math inline">\(O(n)\)</span> per leapfrog (a sum over 10k eigenvalues) while Clenshaw costs <span class="math inline">\(O(\text{order}) \approx 15\)</span>. This validates <code>_resolvent</code> / the differentiable surrogate over the naïve eigenvalue path.</li>
<li><strong>The whole gap is the spatial penalty, not NUTS.</strong> OLS-NUTS <span class="math inline">\(\beta\)</span>-ESS/sec (4227 at <span class="math inline">\(n=2.5\text{k}\)</span>) <span class="math inline">\(&gt;\)</span> Gibbs-SAR (2744): NUTS on a <em>linear</em> model already exceeds Gibbs on a <em>spatial</em> one. SAR-NUTS runs <span class="math inline">\(\sim\!3\times\)</span> slower than its own OLS baseline — the cost of the logdet term plus <span class="math inline">\(\rho\)</span>-geometry (mean tree <span class="math inline">\(\approx 8.5\)</span> leapfrog steps vs OLS <span class="math inline">\(\approx 4.5\)</span>). “Spatial at the speed of linear” is the unmet target; closing it is a geometry problem (<span class="math inline">\(\rho\)</span> reparameterisation), not a logdet one.</li>
</ol>
<p>SLQ’s frozen-probe bias grows with <span class="math inline">\(n\)</span> (KS 0.010 <span class="math inline">\(\to\)</span> 0.043 from <span class="math inline">\(2.5\text{k}\to10\text{k}\)</span>) but stays small; it is the arm whose precompute survives <span class="math inline">\(n \gg 10^5\)</span> / non-planar <span class="math inline">\(W\)</span>.</p>
<p><strong>GPU is the open door (unmeasured).</strong> blackjax is pure-JAX: it vmaps across chains and its per-leapfrog cost is an <span class="math inline">\(O(nk)\)</span> matmul plus a <span class="math inline">\(\mu\)</span>s Clenshaw — both GPU-native. Gibbs’ sequential conjugate draws + stepping-out slice sampler do not parallelise the same way. The CPU deficit could narrow or invert on GPU; this run does not measure it and the claim stays a hypothesis.</p>
</section>
<section id="sec-expC" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Experiment C: panels and the bug NUTS found</h1>
<p>The cross-section verdict (Gibbs <span class="math inline">\(\gg\)</span> NUTS on CPU) does not obviously carry to panels: unit random effects (RE) / many fixed effects (FE) make the posterior high-dimensional, the regime where gradient NUTS is often the better mixer — and the chol-cheb logdet keeps its per-leapfrog cost low (the pytensor logdet is differentiable, so PyMC NUTS already uses it). We benchmark SAR panel FE and RE both ways.</p>
<div class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>panel <span class="op">=</span> pd.read_csv(RESULTS <span class="op">/</span> <span class="st">"panel_shootout.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">"model"</span>, <span class="st">"sampler"</span>, <span class="st">"n_obs"</span>, <span class="st">"wall_s"</span>, <span class="st">"rho_ess_per_s"</span>, <span class="st">"beta_ess_per_s"</span>, <span class="st">"rho_mean"</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>pv <span class="op">=</span> panel[[c <span class="cf">for</span> c <span class="kw">in</span> cols <span class="cf">if</span> c <span class="kw">in</span> panel.columns]].copy()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> (<span class="st">"rho_ess_per_s"</span>, <span class="st">"beta_ess_per_s"</span>):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    pv[c] <span class="op">=</span> pv[c].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>pv[<span class="st">"wall_s"</span>] <span class="op">=</span> pv[<span class="st">"wall_s"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>pv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-panel" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-panel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Panel Gaussian: all sampler × backend combinations (Experiment C), with first-call compilation excluded via warmup. Gibbs/numpy wins on FE; NUTS/pymc wins on RE at n_obs=1000; nutpie wins on RE at n_obs=2250. SARPanelRE does not support Gibbs/jax. All agree on ρ ≈ 0.49–0.52.
</figcaption>
<div aria-describedby="tbl-panel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">model</th>
<th data-quarto-table-cell-role="th">sampler</th>
<th data-quarto-table-cell-role="th">n_obs</th>
<th data-quarto-table-cell-role="th">wall_s</th>
<th data-quarto-table-cell-role="th">rho_ess_per_s</th>
<th data-quarto-table-cell-role="th">beta_ess_per_s</th>
<th data-quarto-table-cell-role="th">rho_mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>SARPanelFE</td>
<td>gibbs-numpy</td>
<td>1000</td>
<td>1.4</td>
<td>2879.0</td>
<td>2484.4</td>
<td>0.4915</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>SARPanelFE</td>
<td>gibbs-jax</td>
<td>1000</td>
<td>2.2</td>
<td>1877.8</td>
<td>1682.2</td>
<td>0.4920</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>SARPanelFE</td>
<td>nuts-pymc</td>
<td>1000</td>
<td>3.1</td>
<td>908.7</td>
<td>892.1</td>
<td>0.4915</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>SARPanelFE</td>
<td>nuts-blackjax</td>
<td>1000</td>
<td>6.8</td>
<td>319.4</td>
<td>338.6</td>
<td>0.4926</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>SARPanelFE</td>
<td>nuts-nutpie</td>
<td>1000</td>
<td>4.5</td>
<td>536.0</td>
<td>494.1</td>
<td>0.4918</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>SARPanelRE</td>
<td>gibbs-numpy</td>
<td>1000</td>
<td>2.4</td>
<td>1567.9</td>
<td>539.0</td>
<td>0.4917</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>SARPanelRE</td>
<td>nuts-pymc</td>
<td>1000</td>
<td>4.2</td>
<td>1759.9</td>
<td>903.6</td>
<td>0.4949</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>SARPanelRE</td>
<td>nuts-blackjax</td>
<td>1000</td>
<td>6.5</td>
<td>929.2</td>
<td>491.0</td>
<td>0.4955</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>SARPanelRE</td>
<td>nuts-nutpie</td>
<td>1000</td>
<td>5.1</td>
<td>971.9</td>
<td>568.2</td>
<td>0.4955</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>SARPanelFE</td>
<td>gibbs-numpy</td>
<td>2250</td>
<td>2.2</td>
<td>1741.6</td>
<td>1758.6</td>
<td>0.5222</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>SARPanelFE</td>
<td>gibbs-jax</td>
<td>2250</td>
<td>2.2</td>
<td>1725.3</td>
<td>1771.3</td>
<td>0.5218</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>SARPanelFE</td>
<td>nuts-pymc</td>
<td>2250</td>
<td>3.3</td>
<td>861.8</td>
<td>927.6</td>
<td>0.5216</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>SARPanelFE</td>
<td>nuts-blackjax</td>
<td>2250</td>
<td>6.0</td>
<td>392.3</td>
<td>407.9</td>
<td>0.5213</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>SARPanelFE</td>
<td>nuts-nutpie</td>
<td>2250</td>
<td>5.4</td>
<td>427.0</td>
<td>417.9</td>
<td>0.5211</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>SARPanelRE</td>
<td>gibbs-numpy</td>
<td>2250</td>
<td>6.2</td>
<td>631.8</td>
<td>167.7</td>
<td>0.5227</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>SARPanelRE</td>
<td>nuts-pymc</td>
<td>2250</td>
<td>24.9</td>
<td>232.4</td>
<td>95.3</td>
<td>0.5268</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>SARPanelRE</td>
<td>nuts-blackjax</td>
<td>2250</td>
<td>10.1</td>
<td>487.7</td>
<td>216.8</td>
<td>0.5270</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>SARPanelRE</td>
<td>nuts-nutpie</td>
<td>2250</td>
<td>5.4</td>
<td>589.0</td>
<td>347.1</td>
<td>0.5269</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><strong>Finding 1: Gibbs/numpy wins on FE; NUTS wins on RE — and the best NUTS backend depends on <span class="math inline">\(n\)</span>.</strong> On FE, Gibbs/numpy leads at both sizes (2879 / 1742 <span class="math inline">\(\rho\)</span>-ESS/s), with Gibbs/jax matching at <span class="math inline">\(n_{\text{obs}}=2250\)</span> (1725) — the JAX backend amortises compilation by this size. NUTS/pymc is the best NUTS on FE (909 / 862), <span class="math inline">\(\sim\!3\times\)</span> behind Gibbs.</p>
<p>On RE, NUTS <strong>beats</strong> Gibbs/numpy at <span class="math inline">\(n_{\text{obs}}=1000\)</span>: pymc 1760 vs Gibbs 1568, and nutpie 972, blackjax 929. At <span class="math inline">\(n_{\text{obs}}=2250\)</span>, nutpie wins (589 vs Gibbs 632), with blackjax close (488) and pymc slower (232). The RE regime — with its higher-dimensional random-effects posterior — is where gradient NUTS is the better mixer, and the <span class="math inline">\(\mu\)</span>s chol-cheb logdet keeps its per-leapfrog cost low. <code>SARPanelRE</code> only supports the numpy Gibbs backend (no JAX), so the JAX-vs-numpy Gibbs comparison is FE-only here.</p>
<p>The NUTS backend ranking shifts with <span class="math inline">\(n\)</span>: pymc is fastest at <span class="math inline">\(n_{\text{obs}}=1000\)</span> (cheap graph compile), but nutpie wins at 2250 (numba kernels amortise at larger <span class="math inline">\(n\)</span>). Blackjax-via-PyMC is consistently middle.</p>
<p><strong>Finding 2: 🐞→✅ Bug discovered and FIXED — <code>SARPanelFE</code> JAX-Gibbs <span class="math inline">\(\rho\)</span> double-counted <span class="math inline">\(T\)</span>.</strong> The bug was discovered when an earlier run showed FE Gibbs reporting <span class="math inline">\(\rho \approx 0.19\)</span>–<span class="math inline">\(0.21\)</span> (<span class="math inline">\(T=10\)</span>) while FE NUTS gave <span class="math inline">\(\rho \approx 0.49\)</span> ✓. Root cause (JAX backend only): the panel passes the <span class="math inline">\(NT\times NT\)</span> block-diagonal lag <span class="math inline">\(I_T \otimes W\)</span> as the sampler’s <code>W_sparse</code>, whose logdet <em>already</em> equals <span class="math inline">\(T\cdot\log|I_N-\rho W|\)</span>; <code>_build_logdet_jax</code> then multiplied by <span class="math inline">\(T = \text{self.T}\)</span> again <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(T^2\cdot\log\)</span>, an over-strong Jacobian pushing <span class="math inline">\(\rho \to 0\)</span> (<span class="math inline">\(T^2\)</span> vs <span class="math inline">\(T\)</span> <span class="math inline">\(\Rightarrow\)</span> worse with <span class="math inline">\(T\)</span>). The numpy backend used the model’s <span class="math inline">\(N\times N\)</span> <span class="math inline">\(W\)</span> and was always correct; <code>SARPanelRE</code> only supports numpy; the eigenvalue method used length-<span class="math inline">\(N\)</span> <code>W_eigs</code> — so only FE with <code>auto</code>→JAX and a non-eigenvalue logdet was hit. <strong>Fix</strong>: extract the per-period block <span class="math inline">\(W[:N,:N]\)</span> in <code>_build_logdet_jax</code> (no-op for cross-section <span class="math inline">\(T=1\)</span>), so <span class="math inline">\(T\)</span> applies once. Verified: the current run shows FE Gibbs and FE NUTS now agreeing at <span class="math inline">\(\rho \approx 0.49\)</span> (was 0.19 vs 0.49 pre-fix). Regression <code>tests/test_samplers/test_panel_fe_jax_logdet.py</code> pins the JAX logdet to <span class="math inline">\(T \times\)</span> exact.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>This is the strongest illustration of why a trustworthy gradient path matters.</strong> NUTS was right where Gibbs was silently wrong. A practitioner trusting the pre-fix Gibbs posterior would have concluded “no spatial dependence” from <span class="math inline">\(\rho \approx 0.2\)</span> when the truth was <span class="math inline">\(\rho = 0.5\)</span>. The independent, gradient-based sampler caught a defect that the single-path Gibbs regression test (tolerance 0.25) had missed.</p>
</div>
</div>
</section>
<section id="sec-expD" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Experiment D: unrestricted flow logdet at scale</h1>
<p>The unrestricted three-parameter LeSage–Pace (2008) flow model (see <a href="#sec-literature" class="quarto-xref">Section&nbsp;9</a>) has system matrix <span class="math inline">\(W_F = \rho_d(I\otimes W) + \rho_o(W\otimes I) + \rho_w(W\otimes W)\)</span> with <span class="math inline">\(N = n^2\)</span> and <strong>directed</strong> <span class="math inline">\(W\)</span>. Two dead ends at real flow sizes: the eigendecomposition is out past <span class="math inline">\(n \approx 2\text{k}\)</span> (complex spectrum, directed), and the multinomial <code>"traces"</code> value method noise-amplifies at scale. What <em>does</em> scale is the resolvent-Kronecker gradient</p>
<p><span class="math display">\[
g_k(\rho) \;=\; -\operatorname{tr}\!\big(W_k (I_N - W_F)^{-1}\big),
\qquad W_k \in \{I\otimes W,\; W\otimes I,\; W\otimes W\},
\]</span></p>
<p>a single resolvent trace per component, estimated matvec-only (Hutchinson probes + Kronecker GMRES solves). The flow value is recovered by integrating the gradient along the ray <span class="math inline">\(0 \to \rho\)</span>. The full script is in <code>flow_resolvent_study.py</code>.</p>
<section id="gate-a-gradient-accuracy-improves-with-n" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="gate-a-gradient-accuracy-improves-with-n"><span class="header-section-number">8.1</span> Gate A: gradient accuracy improves with <span class="math inline">\(N\)</span></h2>
<p>For fixed probe count <span class="math inline">\(P\)</span> the relative error of <span class="math inline">\(g\)</span> follows <span class="math inline">\(\sim 1/\sqrt{N\cdot P}\)</span> — it <em>sharpens</em> as the flow grows, the opposite scaling from the eigendecomposition.</p>
<div class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>flow <span class="op">=</span> pd.read_csv(RESULTS <span class="op">/</span> <span class="st">"flow_resolvent_study.csv"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ga <span class="op">=</span> flow[flow[<span class="st">"gate"</span>] <span class="op">==</span> <span class="st">"gradient_accuracy"</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># pivot: key -&gt; value, group by N</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n_val <span class="kw">in</span> <span class="bu">sorted</span>(ga[ga[<span class="st">"key"</span>].<span class="bu">str</span>.startswith(<span class="st">"N"</span>) <span class="op">&amp;</span> ga[<span class="st">"key"</span>].<span class="bu">str</span>.endswith(<span class="st">"_N"</span>)][<span class="st">"value"</span>].astype(<span class="bu">int</span>).unique()):</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> ga[ga[<span class="st">"key"</span>].<span class="bu">str</span>.startswith(<span class="ss">f"N</span><span class="sc">{</span>n_val<span class="sc">}</span><span class="ss">_"</span>)]</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    rec <span class="op">=</span> {<span class="st">"N"</span>: n_val}</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _, r <span class="kw">in</span> sub.iterrows():</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        rec[r[<span class="st">"key"</span>].split(<span class="st">"_"</span>, <span class="dv">1</span>)[<span class="dv">1</span>]] <span class="op">=</span> <span class="bu">float</span>(r[<span class="st">"value"</span>])</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    rows.append(rec)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>fg <span class="op">=</span> pd.DataFrame(rows)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> fg.columns:</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> c <span class="op">!=</span> <span class="st">"N"</span>:</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        fg[c] <span class="op">=</span> fg[c].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>fg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-flow-grad" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-flow-grad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Flow gradient accuracy vs N (Experiment D, Gate A). Std% and bias% of the stochastic Kronecker gradient against the exact eigenvalue gradient. The std% falls as N grows (1/√(NP) scaling).
</figcaption>
<div aria-describedby="tbl-flow-grad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">N</th>
<th data-quarto-table-cell-role="th">std_pct_g_d</th>
<th data-quarto-table-cell-role="th">std_pct_g_o</th>
<th data-quarto-table-cell-role="th">bias_pct_g_d</th>
<th data-quarto-table-cell-role="th">bias_pct_g_o</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>400.0</td>
<td>36.5</td>
<td>88.7</td>
<td>24.3</td>
<td>28.8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>900.0</td>
<td>29.3</td>
<td>38.1</td>
<td>16.5</td>
<td>14.4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1600.0</td>
<td>27.0</td>
<td>26.3</td>
<td>2.2</td>
<td>24.3</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="gate-b-sampler-validation" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="gate-b-sampler-validation"><span class="header-section-number">8.2</span> Gate B: sampler validation</h2>
<p>The MALA-on-<span class="math inline">\(\rho\)</span> within conjugate <span class="math inline">\(\beta, \sigma^2\)</span> Gibbs sampler (<code>sample_flow_resolvent</code>) is validated against an exact-eigenvalue logdet backend at small <span class="math inline">\(n\)</span> so the posterior is known-good before the estimator replaces it. The recovered <span class="math inline">\(\rho\)</span> matches the truth within Monte Carlo error at <span class="math inline">\(n=18\)</span> (<span class="math inline">\(N=324\)</span>); ESS is low because the problem is tiny, but the <em>correctness</em> gate — does it target the right posterior — passes.</p>
<div class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ess <span class="op">=</span> flow[flow[<span class="st">"gate"</span>] <span class="op">==</span> <span class="st">"ess_per_sec"</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>rec <span class="op">=</span> {}</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _, r <span class="kw">in</span> ess.iterrows():</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        rec[r[<span class="st">"key"</span>]] <span class="op">=</span> <span class="bu">float</span>(r[<span class="st">"value"</span>])</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> (<span class="pp">ValueError</span>, <span class="pp">TypeError</span>):</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        rec[r[<span class="st">"key"</span>]] <span class="op">=</span> r[<span class="st">"value"</span>]</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>pd.DataFrame([rec])[[<span class="st">"n"</span>, <span class="st">"N"</span>, <span class="st">"backend"</span>, <span class="st">"wall_s"</span>, <span class="st">"ess_min_rho"</span>, <span class="st">"ess_per_sec"</span>, <span class="st">"rho_d_mean"</span>, <span class="st">"rho_o_mean"</span>, <span class="st">"rho_w_mean"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-flow-ess" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-flow-ess-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Flow sampler validation (Experiment D, Gate B). ρ-ESS/sec against an exact-eigenvalue logdet backend (known-good posterior). CPU baseline; the GPU/JAX Kronecker path is the open lever.
</figcaption>
<div aria-describedby="tbl-flow-ess-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">N</th>
<th data-quarto-table-cell-role="th">backend</th>
<th data-quarto-table-cell-role="th">wall_s</th>
<th data-quarto-table-cell-role="th">ess_min_rho</th>
<th data-quarto-table-cell-role="th">ess_per_sec</th>
<th data-quarto-table-cell-role="th">rho_d_mean</th>
<th data-quarto-table-cell-role="th">rho_o_mean</th>
<th data-quarto-table-cell-role="th">rho_w_mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>18.0</td>
<td>324.0</td>
<td>exact</td>
<td>1.647048</td>
<td>8.721443</td>
<td>5.295197</td>
<td>0.269694</td>
<td>0.162309</td>
<td>0.189043</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p><strong>The CPU numbers here are the baseline; the payoff is the GPU path.</strong> The Kronecker matvecs are batched <span class="math inline">\(n\times n\)</span> matmuls, GPU-native — exactly where the CPU deficit of <a href="#sec-expB" class="quarto-xref">Section&nbsp;6</a> can invert.</p>
</section>
</section>
<section id="sec-literature" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> The three-<span class="math inline">\(\rho\)</span> flow model in the literature</h1>
<section id="the-lesagepace-spatial-autoregressive-interaction-model" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="the-lesagepace-spatial-autoregressive-interaction-model"><span class="header-section-number">9.1</span> The LeSage–Pace spatial-autoregressive interaction model</h2>
<p><span class="citation" data-cites="lesagepace2008">LeSage and Pace (<a href="#ref-lesagepace2008" role="doc-biblioref">2008</a>)</span> introduced the spatial-autoregressive origin–destination (OD) flow model, extending the conventional gravity / spatial interaction model to allow spatial dependence between flows. <span class="citation" data-cites="thomasagnan2014">Thomas-Agnan and LeSage (<a href="#ref-thomasagnan2014" role="doc-biblioref">2014</a>)</span> give the canonical exposition. The model stacks the <span class="math inline">\(n\times n\)</span> flow matrix into an <span class="math inline">\(n^2\times 1\)</span> vector <span class="math inline">\(y\)</span> and specifies</p>
<p><span class="math display">\[
y \;=\; \rho_o W_o y + \rho_d W_d y + \rho_w W_w y + Z\delta + \varepsilon,
\qquad
A \;=\; I_{n^2} - \rho_o W_o - \rho_d W_d + \rho_w W_w,
\]</span></p>
<p>with <span class="math inline">\(W_o = I_n \otimes W\)</span>, <span class="math inline">\(W_d = W \otimes I_n\)</span>, <span class="math inline">\(W_w = W \otimes W\)</span> for a conventional row-standardised <span class="math inline">\(n\times n\)</span> weights matrix <span class="math inline">\(W\)</span> <span class="citation" data-cites="thomasagnan2014">(<a href="#ref-thomasagnan2014" role="doc-biblioref">Thomas-Agnan and LeSage 2014</a>, Eqs. 83.6–83.8)</span>. The three parameters capture <em>origin dependence</em> (<span class="math inline">\(\rho_o\)</span>), <em>destination dependence</em> (<span class="math inline">\(\rho_d\)</span>), and <em>origin–destination dependence</em> (<span class="math inline">\(\rho_w\)</span>): larger flows from origin <span class="math inline">\(A\)</span> to destination <span class="math inline">\(Z\)</span> are accompanied by larger flows from neighbours of <span class="math inline">\(A\)</span> to <span class="math inline">\(Z\)</span>, from <span class="math inline">\(A\)</span> to neighbours of <span class="math inline">\(Z\)</span>, and from neighbours of <span class="math inline">\(A\)</span> to neighbours of <span class="math inline">\(Z\)</span>.</p>
</section>
<section id="the-separable-restriction-and-why-it-is-tractable-but-restrictive" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="the-separable-restriction-and-why-it-is-tractable-but-restrictive"><span class="header-section-number">9.2</span> The separable restriction and why it is tractable but restrictive</h2>
<p>The filter <span class="math inline">\(A\)</span> implies a restriction <span class="math inline">\(\rho_w = -\rho_o\rho_d\)</span> (so that <span class="math inline">\(A = (I - \rho_o W_o)(I - \rho_d W_d)\)</span>). <span class="citation" data-cites="lesagepace2008">LeSage and Pace (<a href="#ref-lesagepace2008" role="doc-biblioref">2008</a>)</span> propose imposing this restriction as a default, under which the log-determinant factorises:</p>
<p><span class="math display">\[
\log|A| \;=\; n\,\log|I - \rho_d W| \;+\; n\,\log|I - \rho_o W|.
\]</span></p>
<p>This is <em>two single-parameter</em> logdets — exactly the problem the companion log-determinant paper solves exactly and cheaply. It is the tractable case, and it is what the <code>neighbayes</code> separable flow factory (<code>_logdet/_flow.py::make_flow_separable_logdet</code>) implements.</p>
<p>But the restriction is misspecified when genuine origin–destination dependence is present: <span class="math inline">\(\rho_w \neq -\rho_o\rho_d\)</span> means flows between <em>neighbours of the origin</em> and <em>neighbours of the destination</em> move together in a way the separable filter cannot represent. The applied literature (see <span class="citation" data-cites="thomasagnan2014">Thomas-Agnan and LeSage (<a href="#ref-thomasagnan2014" role="doc-biblioref">2014</a>)</span> §83.4) increasingly wants the <em>unrestricted</em> model, and <span class="citation" data-cites="lesagepace2008">LeSage and Pace (<a href="#ref-lesagepace2008" role="doc-biblioref">2008</a>)</span> themselves note the restriction “need not be imposed during estimation.”</p>
</section>
<section id="why-the-unrestricted-case-is-hard-in-the-literature" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="why-the-unrestricted-case-is-hard-in-the-literature"><span class="header-section-number">9.3</span> Why the unrestricted case is hard in the literature</h2>
<p><span class="citation" data-cites="lesagepace2008">LeSage and Pace (<a href="#ref-lesagepace2008" role="doc-biblioref">2008</a>)</span> and <span class="citation" data-cites="lesage2009">LeSage and Pace (<a href="#ref-lesage2009" role="doc-biblioref">2009</a>)</span> / <span class="citation" data-cites="leesage2015">LeSage and Pace (<a href="#ref-leesage2015" role="doc-biblioref">2015</a>)</span> provide ML and Bayesian MCMC estimation that exploit small-dimension moment matrices (Eqs. 83.3–83.5 of <span class="citation" data-cites="thomasagnan2014">Thomas-Agnan and LeSage (<a href="#ref-thomasagnan2014" role="doc-biblioref">2014</a>)</span>) — clever algebra that avoids storing the <span class="math inline">\(n^2\times R\)</span> design matrices. But both still require <span class="math inline">\(\log|A|\)</span> at every <span class="math inline">\(\rho\)</span> value the optimiser or sampler visits, and, for any gradient-based method, the <span class="math inline">\(\rho\)</span>-derivative</p>
<p><span class="math display">\[
\frac{\partial}{\partial \rho_k}\log|A| \;=\; -\operatorname{tr}\!\big(W_k (I_{n^2} - W_F)^{-1}\big),
\qquad k \in \{d, o, w\}.
\]</span></p>
<p>For the unrestricted model with directed <span class="math inline">\(W\)</span>:</p>
<ul>
<li><strong>The eigendecomposition is dead past <span class="math inline">\(n \approx 2\text{k}\)</span>.</strong> Directed <span class="math inline">\(W\)</span> has a complex spectrum, so <span class="math inline">\(\log|A| = \sum \log|1 - \mu_j|\)</span> over the eigenvalues <span class="math inline">\(\mu_j\)</span> of <span class="math inline">\(W_F\)</span>, an <span class="math inline">\(O(n^6)\)</span> operation on the <span class="math inline">\(n^2\times n^2\)</span> matrix. Even the <span class="math inline">\(O(n^3)\)</span> eigendecomposition of the <span class="math inline">\(n\times n\)</span> <span class="math inline">\(W\)</span> that the separable case reuses is unavailable.</li>
<li><strong>The moment-based <code>"traces"</code> value estimator noise-amplifies at scale.</strong> The multinomial coefficients that express <span class="math inline">\(\operatorname{tr}(W_F^k)\)</span> from the traces of <span class="math inline">\(W^k\)</span> blow up Hutchinson error — which is why the <code>"traces"</code> method was removed from <code>neighbayes/_logdet/_flow.py</code>.</li>
</ul>
</section>
<section id="the-resolvent-kronecker-gradient-is-the-first-scalable-eigenvalue-free-unrestricted-path" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="the-resolvent-kronecker-gradient-is-the-first-scalable-eigenvalue-free-unrestricted-path"><span class="header-section-number">9.4</span> The resolvent-Kronecker gradient is the first scalable, eigenvalue-free, unrestricted path</h2>
<p>The contribution of <a href="#sec-expD" class="quarto-xref">Section&nbsp;8</a> is that each gradient component <span class="math inline">\(g_k\)</span> is a <em>single</em> resolvent trace, estimated matvec-only via Kronecker GMRES:</p>
<p><span class="math display">\[
W_F\,\operatorname{vec}(X)
  = \operatorname{vec}\!\big(\rho_d\,WX + \rho_o\,XW^\top + \rho_w\,WXW^\top\big),
\]</span></p>
<p>applied in <span class="math inline">\(O(n\cdot\mathrm{nnz}(W))\)</span>, with the solve <span class="math inline">\((I_N - W_F)^{-\top} z\)</span> done by GMRES on that operator. No eigendecomposition, directed-<span class="math inline">\(W\)</span> safe, and the Hutchinson relative error scales as <span class="math inline">\(1/\sqrt{N\cdot P}\)</span> with <span class="math inline">\(N = n^2\)</span> — so it <strong>improves with the flow sample size</strong>, the opposite scaling from the eigendecomposition.</p>
<p>The flow value is recovered by integrating the gradient along the ray <span class="math inline">\(0 \to \rho\)</span>:</p>
<p><span class="math display">\[
\log|I_N - W_F(\rho)|
  = \int_0^1 \sum_k \rho_k\,g_k(t\rho)\,dt,
\]</span></p>
<p>a 1-D Gauss–Legendre integral of the (scalable) gradient — so the value inherits the gradient’s <span class="math inline">\(1/\sqrt{NP}\)</span> accuracy and also improves with <span class="math inline">\(N\)</span>.</p>
</section>
<section id="connection-to-the-impacts-decomposition" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="connection-to-the-impacts-decomposition"><span class="header-section-number">9.5</span> Connection to the impacts decomposition</h2>
<p><span class="citation" data-cites="thomasagnan2014">Thomas-Agnan and LeSage (<a href="#ref-thomasagnan2014" role="doc-biblioref">2014</a>)</span> (§83.5) set forth the interpretation of spatial interaction models via a decomposition of the total-effects matrix into origin, destination, intraregional, and network effects. The direct-effect traces those summaries need are exactly the resolvent trace: the average direct multiplier <span class="math inline">\(1 - (\rho/n)g(\rho)\)</span> and the cross-direct <span class="math inline">\(-g(\rho)/n\)</span>. The impacts refactor of <a href="#sec-impacts" class="quarto-xref">Section&nbsp;10</a> supplies them without the <span class="math inline">\(O(n^3)\)</span> eigendecomposition — so the same unification that feeds gradient samplers and the cross-section impacts also feeds the flow-model impacts decomposition.</p>
</section>
</section>
<section id="sec-impacts" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Realised win: impacts without eigendecomposition</h1>
<p>The “one object, three consumers” unification (<a href="#sec-consumers" class="quarto-xref">Section&nbsp;3</a>) is realised for impacts. The two direct-effect trace quantities are exactly the logdet gradient:</p>
<ul>
<li>average direct multiplier <span class="math inline">\((1/n)\operatorname{tr}((I-\rho W)^{-1}) = 1 - (\rho/n)g(\rho)\)</span>;</li>
<li>SDM cross direct <span class="math inline">\((1/n)\operatorname{tr}((I-\rho W)^{-1}W) = -g(\rho)/n\)</span>.</li>
</ul>
<p>Previously both were built from the full spectrum via <code>_chunked_eig_means(rho, self._W_eigs)</code>, which triggered the <span class="math inline">\(O(n^3)\)</span> dense eigendecomposition <strong>even for row-standardised <span class="math inline">\(W\)</span></strong> (where the total-effect row sum already had the closed form <span class="math inline">\(1/(1-\rho)\)</span>). They now ride the model’s fast logdet gradient (<code>make_logdet_grad_numpy_vec_fn</code> → <code>_batch_mean_diag</code> / <code>_batch_mean_diag_MW</code>), so a chol-cheb / AAA model computes impacts with <strong>no eigendecomposition at all</strong>.</p>
<div class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>imp <span class="op">=</span> pd.read_csv(RESULTS <span class="op">/</span> <span class="st">"impacts_study.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">"n"</span>, <span class="st">"path"</span>, <span class="st">"wall_s"</span>, <span class="st">"direct"</span>, <span class="st">"indirect"</span>, <span class="st">"total"</span>, <span class="st">"max_abs_diff_vs_eig"</span>, <span class="st">"eig_called"</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>iv <span class="op">=</span> imp[[c <span class="cf">for</span> c <span class="kw">in</span> cols <span class="cf">if</span> c <span class="kw">in</span> imp.columns]].copy()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> (<span class="st">"direct"</span>, <span class="st">"indirect"</span>, <span class="st">"total"</span>, <span class="st">"max_abs_diff_vs_eig"</span>):</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    iv[c] <span class="op">=</span> iv[c].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.4g}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>iv[<span class="st">"wall_s"</span>] <span class="op">=</span> iv[<span class="st">"wall_s"</span>].<span class="bu">map</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.3f}</span><span class="ss">"</span> <span class="cf">if</span> pd.notna(x) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>iv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-impacts" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-impacts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Impacts without eigendecomposition (Experiment E). Wall-time of spatial_effects() on the eigenvalue path vs the chol-cheb resolvent path, and the max abs difference of the posterior-mean direct/indirect/total effects between the two. The resolvent path never calls np.linalg.eig (verified by poisoning it to raise).
</figcaption>
<div aria-describedby="tbl-impacts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">path</th>
<th data-quarto-table-cell-role="th">wall_s</th>
<th data-quarto-table-cell-role="th">direct</th>
<th data-quarto-table-cell-role="th">indirect</th>
<th data-quarto-table-cell-role="th">total</th>
<th data-quarto-table-cell-role="th">max_abs_diff_vs_eig</th>
<th data-quarto-table-cell-role="th">eig_called</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>400</td>
<td>eigenvalue</td>
<td>0.007</td>
<td>2.188</td>
<td>2.594</td>
<td>4.782</td>
<td>0</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>400</td>
<td>cheb_cholesky</td>
<td>0.015</td>
<td>2.178</td>
<td>2.558</td>
<td>4.736</td>
<td>0.04628</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2500</td>
<td>eigenvalue</td>
<td>0.011</td>
<td>2.25</td>
<td>2.793</td>
<td>5.043</td>
<td>0</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>2500</td>
<td>cheb_cholesky</td>
<td>0.071</td>
<td>2.248</td>
<td>2.785</td>
<td>5.033</td>
<td>0.0104</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>10000</td>
<td>cheb_cholesky</td>
<td>0.399</td>
<td>2.217</td>
<td>2.72</td>
<td>4.938</td>
<td>—</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>50176</td>
<td>cheb_cholesky</td>
<td>3.399</td>
<td>2.235</td>
<td>2.725</td>
<td>4.96</td>
<td>—</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>A row-standardised chol-cheb SAR computes <code>spatial_effects()</code> with <code>np.linalg.eig</code> / <code>eigvals</code> poisoned to raise — it never touches them. The resolvent traces match the eigenvalue reference to the chol-cheb gradient accuracy (<span class="math inline">\(\sim\!10^{-5}\)</span>). The remaining, rare eigen dependency is the non-row-standardised <em>total</em> effect: <span class="math inline">\(1'S1\)</span> is not a trace, so no logdet-gradient identity applies, and it keeps the eigenvector bilinear form.</p>
</section>
<section id="sec-discussion" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Discussion</h1>
<p><strong>What is validated and worth keeping regardless of the CPU verdict.</strong></p>
<ul>
<li><code>_resolvent</code> and the numpy gradient factory — impacts at scale without <span class="math inline">\(O(n^3)\)</span> eigendecomposition; nutpie-custom / MALA gradients. Tested, matched-pair correct.</li>
<li>The jax SLQ bug fix (a real defect: dense densification + wrong weights).</li>
<li>The surrogate-logdet-for-NUTS result: chol-cheb / <code>_resolvent</code> is <span class="math inline">\(2\times\)</span> faster inside the leapfrog than the eigenvalue logdet — the right ingredient for <em>any</em> future gradient-based spatial sampler.</li>
<li>The unrestricted flow resolvent-Kronecker gradient — the first scalable, eigenvalue-free path for the LeSage–Pace model with <span class="math inline">\(\rho_w \neq -\rho_o\rho_d\)</span>.</li>
<li>The <code>SARPanelFE</code> JAX-Gibbs bug fix — independent evidence that a trustworthy gradient path has scientific value beyond throughput.</li>
</ul>
<p><strong>What is open.</strong></p>
<ul>
<li><strong>GPU is the sole open gate that would change the verdict.</strong> Re-run <a href="#sec-expB" class="quarto-xref">Section&nbsp;6</a> and <a href="#sec-expD" class="quarto-xref">Section&nbsp;8</a> on a GPU (blackjax <code>vmap</code> over chains; larger <span class="math inline">\(n\)</span>). If SAR-NUTS ESS/sec there reaches or beats Gibbs, wire the native path into <code>fit</code> dispatch as the GPU fast path and do the impacts refactor at full scale. Until measured, this is a hypothesis.</li>
<li><strong>Native panel NUTS.</strong> PyMC NUTS already beats Gibbs on RE panels (<span class="math inline">\(\rho\)</span>-ESS/sec 1.3–1.4<span class="math inline">\(\times\)</span> faster); a blackjax-native panel path is the test of whether it can also close the FE gap and scale to larger <span class="math inline">\(N\)</span>.</li>
<li><strong><span class="math inline">\(\rho\)</span> reparameterisation.</strong> The SAR↔︎OLS-NUTS gap is geometry (mean tree <span class="math inline">\(\approx 8.5\)</span> vs <span class="math inline">\(4.5\)</span> leapfrog steps), not logdet cost. A reparameterisation that flattens the <span class="math inline">\(\rho\)</span>-geometry is the route to “spatial at the speed of linear,” not a cheaper logdet.</li>
<li><strong>MALA with an exact-value Metropolis accept.</strong> If one <em>does</em> want fresh-probe unbiased gradients (the CG-resolvent estimator), pair them with a Metropolis accept that uses the exact log-density: the proposal is driven by a noisy gradient, but the accept step keeps the target exact. This isolates “what does an unbiased per-step gradient buy/cost” from “is the target right.” Not benchmarked here; the frozen-probe SLQ bias is small at feasible <span class="math inline">\(p\)</span> in the planar regime, so the pseudo-marginal / Russian-roulette fallback <span class="citation" data-cites="lyne2015 filippone2014">(<a href="#ref-lyne2015" role="doc-biblioref">Lyne et al. 2015</a>; <a href="#ref-filippone2014" role="doc-biblioref">Filippone and Girolami 2014</a>)</span> is not yet needed.</li>
</ul>
<p><strong>Lineage.</strong> The method is new to spatial econometrics but sits in a clear stochastic-trace / Gaussian-process lineage: <span class="citation" data-cites="ubaru2017">Ubaru et al. (<a href="#ref-ubaru2017" role="doc-biblioref">2017</a>)</span> (SLQ), <span class="citation" data-cites="dong2017">Dong et al. (<a href="#ref-dong2017" role="doc-biblioref">2017</a>)</span> (scalable logdets for GP kernel learning), <span class="citation" data-cites="gardner2018">Gardner et al. (<a href="#ref-gardner2018" role="doc-biblioref">2018</a>)</span> (GPyTorch / BBMM, matrix-free GP inference with Lanczos-based logdet gradients), <span class="citation" data-cites="filippone2014">Filippone and Girolami (<a href="#ref-filippone2014" role="doc-biblioref">2014</a>)</span> (pseudo-marginal MCMC for GP hyperparameters), and <span class="citation" data-cites="lyne2015">Lyne et al. (<a href="#ref-lyne2015" role="doc-biblioref">2015</a>)</span> (Russian-roulette unbiased estimators inside exact MCMC). The frozen-probe / surrogate-derivative idea is the spatial-econometric analog of the fixed-probe Lanczos logdet used in GPyTorch, transferred to the <span class="math inline">\(\rho\)</span>-parametric setting the spatial Jacobian requires.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-betancourt2017" class="csl-entry" role="listitem">
Betancourt, Michael. 2017. <span>“A Conceptual Introduction to <span>Hamiltonian</span> <span>Monte</span> <span>Carlo</span>.”</span> <em>arXiv Preprint arXiv:1701.02434</em>.
</div>
<div id="ref-dong2017" class="csl-entry" role="listitem">
Dong, Kun, David Eriksson, Hannes Nickisch, David Bindel, and Andrew Gordon Wilson. 2017. <span>“Scalable Log Determinants for Gaussian Process Kernel Learning.”</span> <em>Advances in Neural Information Processing Systems</em> 30.
</div>
<div id="ref-filippone2014" class="csl-entry" role="listitem">
Filippone, Maurizio, and Mark Girolami. 2014. <span>“Pseudo-Marginal Bayesian Inference for Gaussian Processes.”</span> <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em> 36 (11): 2214–26.
</div>
<div id="ref-gardner2018" class="csl-entry" role="listitem">
Gardner, Jacob R., Geoff Pleiss, David Bindel, Kilian Q. Weinberger, and Andrew Gordon Wilson. 2018. <span>“<span>GPyTorch</span>: Blackbox Matrix-Matrix <span>Gaussian</span> Process Inference with <span>GPU</span> Acceleration.”</span> <em>Advances in Neural Information Processing Systems</em> 31.
</div>
<div id="ref-hoffman2014" class="csl-entry" role="listitem">
Hoffman, Matthew D., and Andrew Gelman. 2014. <span>“The No-u-Turn Sampler: Adaptively Setting Path Lengths in <span>Hamiltonian</span> <span>Mont</span> <span>Carlo</span>.”</span> <em>Journal of Machine Learning Research</em> 15 (1): 1593–623.
</div>
<div id="ref-hutchinson1990" class="csl-entry" role="listitem">
Hutchinson, Michael F. 1990. <span>“A Stochastic Estimator of the Trace of the Influence Matrix for Laplacian Smoothing Splines.”</span> <em>Communications in Statistics — Simulation and Computation</em> 19 (2): 433–50.
</div>
<div id="ref-lao2020" class="csl-entry" role="listitem">
<span class="nocase">Lao, Junpeng, Colman Suter, Martin Jankowiak, et al.</span> 2020. <span>“<span class="nocase">blackjax</span>: <span>A</span> Library of <span>JAX</span> <span>MCMC</span> Algorithms.”</span> <em>Journal of Open Source Software</em> 5 (51): 2147.
</div>
<div id="ref-lesagepace2008" class="csl-entry" role="listitem">
LeSage, James P., and R. Kelley Pace. 2008. <span>“Spatial Econometric Modeling of Origin-Destination Flows.”</span> <em>Journal of Regional Science</em> 48 (5): 941–67.
</div>
<div id="ref-lesage2009" class="csl-entry" role="listitem">
LeSage, James P., and R. Kelley Pace. 2009. <em>Introduction to Spatial Econometrics</em>. Chapman &amp; Hall/CRC.
</div>
<div id="ref-leesage2015" class="csl-entry" role="listitem">
LeSage, James P., and R. Kelley Pace. 2015. <span>“Spatial Econometric Modeling of Origin-Destination Flows.”</span> <em>Journal of Econometrics</em> 196 (1): 1–20.
</div>
<div id="ref-lyne2015" class="csl-entry" role="listitem">
Lyne, Anne-Marie, Mark Girolami, Heiko Strathmann, Maurizio Filippone, and Zoubin Ghahramani. 2015. <span>“On <span>Russian</span> Roulette Estimates for <span>Bayesian</span> Inference with Doubly-Intractable Likelihoods.”</span> <em>Statistical Science</em> 30 (4): 443–67.
</div>
<div id="ref-ord1975" class="csl-entry" role="listitem">
Ord, J. K. 1975. <span>“Estimation Methods for Models of Spatial Interaction.”</span> <em>Journal of the American Statistical Association</em> 70 (349): 120–26.
</div>
<div id="ref-patil2024" class="csl-entry" role="listitem">
<span class="nocase">Pati, Sayan, James DeLiso, Akshat Arya, et al.</span> 2024. <span>“<span>PyMC</span> V5: A Unified, Programmable Bayesian Statistical Framework.”</span> <em>Journal of Statistical Software</em> 73 (1).
</div>
<div id="ref-thomasagnan2014" class="csl-entry" role="listitem">
Thomas-Agnan, Christine, and James P. LeSage. 2014. <span>“Spatial Econometric OD-Flow Models.”</span> In <em>Handbook of Regional Science</em>, edited by Manfred M. Fischer and Peter Nijkamp. Springer-Verlag.
</div>
<div id="ref-ubaru2017" class="csl-entry" role="listitem">
Ubaru, Shashanka, Jie Chen, and Yousef Saad. 2017. <span>“Fast Estimation of Tr(f(a)) via Stochastic Lanczos Quadrature.”</span> <em>SIAM Journal on Matrix Analysis and Applications</em> 38 (4): 1075–99.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>